jobs:
- name: first-job
  plan:
  - get: source-code
    trigger: true
  - get: onboarding-image
  - task: hello
    file: source-code/tasks/hello.yml

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/amakhija/concourse_onboarding.git
    branch: master
    skip_ssl_verification: true

- name: onboarding-image
  type: docker-image
  source:
    repository: amakhija/onboarding-pivotal
